# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plat < Formula
  desc "Domain lookup via WHOIS and RDAP with per-field source provenance"
  homepage "https://github.com/patramsey/plat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patramsey/plat/releases/download/v0.1.0/plat_0.1.0_darwin_amd64.tar.gz"
      sha256 "f3cbd319105e4cb2ea05dd64abb6a4f16b8726645eeb10161ad0621ff5df2062"

      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patramsey/plat/releases/download/v0.1.0/plat_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba32363098a91898f7c71d66eeecd97684211cc8bd99b45a3308e26ca032074f"

      define_method(:install) do
        bin.install "plat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.1.0/plat_0.1.0_linux_amd64.tar.gz"
      sha256 "48b87192797feba4ca9161d534ae379e457760aaaac6b58421a0765a34a4a0ff"
      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.1.0/plat_0.1.0_linux_arm64.tar.gz"
      sha256 "7ea355125b913ded2ba05631b8fe1be2910baced13de35a00b25fbc7c4f726e6"
      define_method(:install) do
        bin.install "plat"
      end
    end
  end
end
