# This file was generated by GoReleaser. DO NOT EDIT.
cask "namecom" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "50d898fa6564b2fab1ab7c9f8576e439ac3fa9a75e3edd4eaeada0e28387fedd"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a9fed836f195558d867656f4302660480a8f522b438f02d6300a00a16d6d1b5"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4297598d39dc1ebfc9455ae5763537e849c41d2c8e056f3727e8b7988cbe8918"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee4fa4a68612d1206dbf27f97e92098c549bfd31fe00ff7e777ee491ca7f6c4c"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_arm64.tar.gz"
    end
  end

  name "namecom"
  desc "CLI for the name.com domain registrar API"
  homepage "https://github.com/patramsey/namecom-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "namecom"

  # No zap stanza required

end
