# This file was generated by GoReleaser. DO NOT EDIT.
cask "namecom" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "73c22c00210ba3e2aaa0f80e1d95ef11338e816df9c8f01bfba7123e60cd3b96"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1a9aa7607ebfc8cb70e6971287fb357d3f52470b12a8cd98083f3c23d9e5d9c"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "78b25e46c4923e5ee818dfd90241f4dba8eec99a11aaa0f4f200fe1c691d88a8"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e26b02ddc9fb4d47c8c4d810eb7f391e6f7e1a0568bb1e72e96dde874cc55d5"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_arm64.tar.gz"
    end
  end

  name "namecom"
  desc "CLI for the name.com domain registrar API"
  homepage "https://github.com/patramsey/namecom-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "namecom"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/namecom"]
    end
  end

  # No zap stanza required

end
