# This file was generated by GoReleaser. DO NOT EDIT.
cask "namecom" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "66d31b7e74b71ae3d80ab299642025c9a5be27149be5a4f4d89ee7ce61799f7b"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bdf60ffe19337b8195a51880ab5a2d9f07f7004233af29406a6b8d1f2e0a30a"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b4c79e88b3713c2dd68b9f2bbf0cb37cc9be01df1cf0ae5b82f4ad05e98b4f1"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbbb37167a29c2acdeee8a404d8e92f2cf9d2400a46174ce3edab521f116c288"
      url "https://github.com/patramsey/namecom-cli/releases/download/v#{version}/namecom_linux_arm64.tar.gz"
    end
  end

  name "namecom"
  desc "CLI for the name.com domain registrar API"
  homepage "https://github.com/patramsey/namecom-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "namecom"

  # No zap stanza required

end
