# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namecom < Formula
  desc "CLI for the name.com domain registrar API"
  homepage "https://github.com/patramsey/namecom-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.0/namecom_darwin_amd64.tar.gz"
      sha256 "7706e5b9eb6dd0abb566f89d46217b26e7a814527e8193dd42272870d57e09d2"

      define_method(:install) do
        bin.install "namecom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.0/namecom_darwin_arm64.tar.gz"
      sha256 "f203cc820aa6a9163337fb7f4c0089f227397c96011b43e3bb9e6bf14f10480c"

      define_method(:install) do
        bin.install "namecom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.0/namecom_linux_amd64.tar.gz"
      sha256 "278b20b409b71a2483a3a30c90534c7bea738c0de82e055180244eca00ea42d2"
      define_method(:install) do
        bin.install "namecom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.0/namecom_linux_arm64.tar.gz"
      sha256 "a1bb0f4ed3e687542edef11c0a20d2ad574ea68c3444819811130747f795146e"
      define_method(:install) do
        bin.install "namecom"
      end
    end
  end

  def caveats
    <<~EOS
      If you are upgrading from the Homebrew cask (v0.2.4 - v0.3.1), two
      steps remain:

        brew uninstall --cask --force namecom
        brew link namecom

      Without the second, namecom will not be on your PATH. Fresh installs
      need neither.
    EOS
  end
end
