# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namecom < Formula
  desc "CLI for the name.com domain registrar API"
  homepage "https://github.com/patramsey/namecom-cli"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.6/namecom_darwin_amd64.tar.gz"
      sha256 "b125499039827abdda758254584c060e370538e9cc3a661d91f9369b71546d80"

      define_method(:install) do
        bin.install "namecom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.6/namecom_darwin_arm64.tar.gz"
      sha256 "b7d398ccbfccd73e324b83d1761325e70e2cce36bee4290f459e91b24d529424"

      define_method(:install) do
        bin.install "namecom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.6/namecom_linux_amd64.tar.gz"
      sha256 "fa1963f677207d6cfc9d9558fb11fbee3a91370821409ae7f929a797d5c2fd38"
      define_method(:install) do
        bin.install "namecom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/namecom-cli/releases/download/v0.4.6/namecom_linux_arm64.tar.gz"
      sha256 "9ad0522f4e0c12f24d5abdf049eb85c695263e340050b56bb7829aeb0016c6a3"
      define_method(:install) do
        bin.install "namecom"
      end
    end
  end
end
