# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plat < Formula
  desc "Domain lookup via WHOIS and RDAP with per-field source provenance"
  homepage "https://github.com/patramsey/plat"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patramsey/plat/releases/download/v0.3.0/plat_darwin_amd64.tar.gz"
      sha256 "ca47f1b8072b85038538cf3d5ad679d6c8910de361809b854a8fa9a6b8aa6c92"

      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patramsey/plat/releases/download/v0.3.0/plat_darwin_arm64.tar.gz"
      sha256 "e7d99e7c6fd125653ada9444d3449cad06e2a8336e93b334643ea0c6f3888c55"

      define_method(:install) do
        bin.install "plat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.3.0/plat_linux_amd64.tar.gz"
      sha256 "56e849d094f65f09fd5c3ae89d69e35507f7b937e9b49cb19b993d4426ee0711"
      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.3.0/plat_linux_arm64.tar.gz"
      sha256 "06a502772946f6682c71ea1eafd25b17fd1cd59a667619c0d5fe6b87b6d5df1b"
      define_method(:install) do
        bin.install "plat"
      end
    end
  end
end
