# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plat < Formula
  desc "Domain, IP, and ASN lookup via WHOIS and RDAP with per-field source provenance"
  homepage "https://github.com/patramsey/plat"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patramsey/plat/releases/download/v0.7.0/plat_darwin_amd64.tar.gz"
      sha256 "20aeb6e577d3467154254b2fb775cd1170e8b68c751fe9346272ec25736de83a"

      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patramsey/plat/releases/download/v0.7.0/plat_darwin_arm64.tar.gz"
      sha256 "2fc725ddd28fb15462fc425d54c220bd7ea4ad4ce7f8b8594e8d6a0dbdcaa028"

      define_method(:install) do
        bin.install "plat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.7.0/plat_linux_amd64.tar.gz"
      sha256 "5994e67c119c49a2a3afc5886b851c78bb17432857289b46b8bda1d46157d9c7"
      define_method(:install) do
        bin.install "plat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patramsey/plat/releases/download/v0.7.0/plat_linux_arm64.tar.gz"
      sha256 "0f9e57474b0606955411e624c9e7bd43408dadc4487211ede2a476dc89cf6c20"
      define_method(:install) do
        bin.install "plat"
      end
    end
  end
end
